### ISSUE TITLE
Move the light-controller view to the portal-view under controller sidebar menu

### ISSUE THREAD

**Issue by stevehu** [networknt/portal-view#77]
The origianl UI is located at https://github.com/networknt/light-controller/tree/master/view

**Comment by haycmaster** [comment]
Branch add-light-controller-view created

**Comment by haycmaster** [comment]
Hi Steve,

I got this error when logging into portal-view at local.


[image: image.png]


Steve Cheng

**Comment by stevehu** [comment]
It looks like the image is not pasted. Do you want to have a chat in zoom tonight or tomorrow?

**Comment by haycmaster** [comment]
Hi, we can chat now
